chore: update

diff --git a/.github/workflows/check-base-branch.yml b/.github/workflows/check-base-branch.yml
--- a/.github/workflows/check-base-branch.yml
+++ b/.github/workflows/check-base-branch.yml
@@ -19,11 +19,9 @@ jobs:
       - name: Check if base branch is merged into development branch
         run: |
           git merge-base --is-ancestor origin/main HEAD
-          if [ $? -ne 0 ]; then
-            echo "baseブランチとの差分があります。最新のmainブランチをマージしてください"
+          if ! git merge-base --is-ancestor origin/HEAD HEAD; then
+            echo "ERROR: HEAD is not based on upstream HEAD"
             exit 1
-          else
-            echo "baseブランチとの差分はありません"
           fi
 
       - name: Send Slack notification
